// <auto-generated />
using System;
using Genesis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genesis.Data.Migrations
{
    [DbContext(typeof(GenesisContext))]
    [Migration("20260430000215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Core.Entities.Agrupador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AplicaIVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripAgrupador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsIVADescontable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreAgrupador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Agrupadores");
                });

            modelBuilder.Entity("Core.Entities.ImpuestosTaxes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AgrupadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionImpuesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Naturaleza")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorImpuesto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgrupadorId");

                    b.ToTable("ImpuestosTaxes");
                });

            modelBuilder.Entity("Core.Entities.ItemActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionItemActividad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreItemActividad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemActividades");
                });

            modelBuilder.Entity("Core.Entities.MaestroPpto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbrePlantillaPPto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelEstructuraPlantilla")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePlantilla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCostoPlantillaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VersionPlantilla")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoCostoPlantillaId");

                    b.ToTable("MaestroPptos");
                });

            modelBuilder.Entity("Core.Entities.RecursoUnitario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agrupador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRecursoUnitario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoRecurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitarioBruto")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecursoUnitarios");
                });

            modelBuilder.Entity("Core.Entities.TipoCosto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbreTipoCosto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionTipoCosto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposCosto");
                });

            modelBuilder.Entity("Core.Entities.TipoRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbrTipoRecurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionTipoRecurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposRecurso");
                });

            modelBuilder.Entity("Core.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbreUnidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionUnidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Esref")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMedida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("UnidadConversion")
                        .HasColumnType("REAL");

                    b.Property<string>("UnidadRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombrePila")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UltimoIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Agrupador", b =>
                {
                    b.HasOne("Core.Entities.TipoRecurso", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Core.Entities.ImpuestosTaxes", b =>
                {
                    b.HasOne("Core.Entities.Agrupador", null)
                        .WithMany("OtrosImpuestos")
                        .HasForeignKey("AgrupadorId");
                });

            modelBuilder.Entity("Core.Entities.MaestroPpto", b =>
                {
                    b.HasOne("Core.Entities.TipoCosto", "TipoCostoPlantilla")
                        .WithMany()
                        .HasForeignKey("TipoCostoPlantillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCostoPlantilla");
                });

            modelBuilder.Entity("Core.Entities.Agrupador", b =>
                {
                    b.Navigation("OtrosImpuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
